/**
 * Grounded generation for the knowledge layer (brief §24, §25).
 *
 * The response and the quote brief are composed ONLY from facts present in the
 * retrieved brief. Pricing, availability, technical approval and delivery
 * commitments are never invented: where the records do not settle something,
 * the output says so and leaves it for a human.
 */
import type { EnquiryBrief, BriefField } from './brief.ts';

const find = (b: EnquiryBrief, label: string): BriefField | undefined =>
  b.fields.find((f) => f.label === label);

/** A customer-facing email draft. Deliberately commits to nothing. */
export function composeCustomerResponse(b: EnquiryBrief): string {
  const customer = b.customerName ?? 'the customer';
  const requirement = b.requirement ?? 'the tooling requirement';
  const delivery = find(b, 'Required delivery')?.value ?? null;
  const supplier = find(b, 'Latest supplier information');
  const previous = find(b, 'Previous interactions');

  const L: string[] = [];
  L.push(`Subject: Your enquiry — ${requirement}`, '');
  L.push('Dear colleague,', '');
  L.push(
    `Thank you for your enquiry regarding ${requirement.toLowerCase()}. ` +
    'I am confirming current availability and pricing with our supplier and will come back to you ' +
    'with a full quotation.',
  );
  L.push('');

  if (previous) {
    L.push(
      'We have supplied comparable tooling to your team previously, so we already hold the ' +
      'relevant part references on your account.',
    );
    L.push('');
  }

  if (delivery) {
    if (supplier?.conflict) {
      L.push(
        `I note your requirement for delivery within ${delivery.toLowerCase()}. Our supplier position ` +
        'has recently changed and I am confirming the current lead time in writing before I offer ' +
        'you a delivery date. I will confirm this alongside the quotation.',
      );
    } else {
      L.push(
        `I note your requirement for delivery within ${delivery.toLowerCase()}. I will confirm ` +
        'whether that is achievable once the supplier has confirmed current availability.',
      );
    }
    L.push('');
  }

  L.push(
    'Please note that applicability of this tooling to your specific aircraft variant will be ' +
    'confirmed by our engineering team before we make any statement of suitability.',
  );
  L.push('');
  L.push('I will revert within two working days.', '');
  L.push('Kind regards,');
  L.push(find(b, 'Internal owner')?.value.split(',')[0] ?? 'Field International');
  L.push('Field International');

  return L.join('\n');
}

export interface QuoteBrief {
  sections: Array<{ heading: string; lines: string[]; interpretation?: boolean }>;
  text: string;
}

/** The internal preparation brief a quoting colleague would actually need. */
export function composeQuoteBrief(b: EnquiryBrief, catalogueMatches: Array<{ partNumber: string | null; name: string; leadTimeDays: number | null }> = []): QuoteBrief {
  const val = (label: string) => find(b, label)?.value ?? 'Not established from the available records';
  const supplier = find(b, 'Latest supplier information');

  const sections: QuoteBrief['sections'] = [
    { heading: 'Customer', lines: [val('Customer'), `Account owner: ${val('Internal owner')}`] },
    { heading: 'Requirement', lines: [val('Requirement'), `Required delivery: ${val('Required delivery')}`] },
    {
      heading: 'Relevant catalogue items',
      lines: catalogueMatches.length
        ? catalogueMatches.map((m) =>
            `${m.partNumber ?? '—'}  ${m.name.slice(0, 70)}  ` +
            `${m.leadTimeDays !== null ? `lead ${m.leadTimeDays} days` : 'lead time not published'}`)
        : ['No catalogue items attached to this brief.'],
    },
    { heading: 'Previous quote', lines: [val('Previous quote')] },
    { heading: 'Previous pricing basis', lines: [`Historical lead time quoted: ${val('Historical lead time quoted')}`] },
    {
      heading: 'Current supplier information',
      lines: supplier?.conflict
        ? [
            supplier.value,
            'CONFLICT — sources disagree:',
            ...supplier.conflict.positions.map((p) => `  • ${p.value}  (${p.citation.path})`),
            'This must be confirmed in writing before a delivery position is offered.',
          ]
        : [val('Latest supplier information')],
    },
    {
      heading: 'Technical review required',
      lines: [
        'Yes — catalogue applicability is recorded at aircraft model level only.',
        'Variant-level suitability requires Engineering confirmation before any statement is made.',
      ],
      interpretation: true,
    },
    {
      heading: 'Commercial review required',
      lines: [
        'Yes — pricing is not carried by this brief and must be prepared by Commercial.',
        'No price, discount or delivery commitment has been generated by the AI layer.',
      ],
    },
    { heading: 'Open questions', lines: b.openQuestions },
    { heading: 'Recommended actions', lines: [b.recommendedNextStep], interpretation: true },
  ];

  const text = [
    'QUOTE PREPARATION BRIEF', '',
    ...sections.flatMap((s) => [s.heading.toUpperCase(), ...s.lines.map((l) => `  ${l}`), '']),
    'Synthetic demonstration data. Prepared by an AI assistant from retrieved internal records.',
    'All pricing, delivery and technical suitability remain subject to human review.',
  ].join('\n');

  return { sections, text };
}
